# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "Cageforge",
    "CageforgeConfigurationError",
    "CageforgeError",
    "CageforgeInitializationError",
    "CageforgeLaunchError",
    "CageforgeProcessError",
    "CageforgeStreamError",
    "CageforgeWindowsSetupError",
    "ProcessResult",
    "RuntimeContext",
    "SandboxProcess",
    "UnsupportedPlatformError",
    "WindowsSetup",
    "native_target",
]

@typing.final
class Cageforge:
    r"""
    A reusable resolved Cageforge runtime.
    """
    @staticmethod
    def profile_names(toml: builtins.str) -> builtins.list[builtins.str]:
        r"""
        Returns validated profile names in deterministic lexical order.
        """
    @staticmethod
    def check_toml(toml: builtins.str, profile_name: typing.Optional[builtins.str] = None, context: typing.Optional[RuntimeContext] = None) -> None:
        r"""
        Checks TOML parsing, profile resolution, and policy composition.
        """
    @staticmethod
    def from_toml(toml: builtins.str, profile_name: typing.Optional[builtins.str] = None, context: typing.Optional[RuntimeContext] = None) -> Cageforge:
        r"""
        Creates a native runtime from TOML and the selected profile.
        """
    @staticmethod
    def from_toml_file(file: builtins.str | os.PathLike[str] | pathlib.Path, profile_name: typing.Optional[builtins.str] = None, context: typing.Optional[RuntimeContext] = None) -> Cageforge:
        r"""
        Reads a TOML file and creates a runtime using its parent directory.
        """
    @staticmethod
    def native_target() -> builtins.str:
        r"""
        Returns the native resource target selected by this interpreter.
        """
    def launch(self, argv: typing.Optional[typing.Sequence[builtins.str]] = None) -> SandboxProcess:
        r"""
        Launches the profile command, or an explicit argv when supplied.
        """
    def close(self) -> None:
        r"""
        Releases the runtime handle. Existing process objects remain owned by
        their own native child boundary.
        """
    def __enter__(self) -> Cageforge: ...
    def __exit__(self, _ty: typing.Optional[typing.Any], _value: typing.Optional[typing.Any], _traceback: typing.Optional[typing.Any]) -> builtins.bool: ...

class CageforgeConfigurationError(CageforgeError):
    r"""
    The TOML configuration or runtime context is invalid.
    """
    ...

class CageforgeError(builtins.Exception):
    r"""
    Base class for errors raised by Cageforge.
    """
    ...

class CageforgeInitializationError(CageforgeError):
    r"""
    The native Cageforge backend could not be initialized.
    """
    ...

class CageforgeLaunchError(CageforgeError):
    r"""
    The native sandbox process could not be launched.
    """
    ...

class CageforgeProcessError(CageforgeError):
    r"""
    A sandbox process lifecycle operation failed.
    """
    ...

class CageforgeStreamError(CageforgeError):
    r"""
    A sandbox standard stream operation failed.
    """
    ...

class CageforgeWindowsSetupError(CageforgeError):
    r"""
    Windows setup provisioning or verification failed.
    """
    ...

@typing.final
class ProcessResult:
    r"""
    The result of a completed sandbox process.
    """
    @property
    def exit_code(self) -> typing.Optional[builtins.int]:
        r"""
        The exit code, or `None` when the OS reports signal-style termination.
        """

@typing.final
class RuntimeContext:
    r"""
    Runtime paths deliberately supplied by the host application.
    """
    @property
    def current_directory(self) -> pathlib.Path:
        r"""
        Absolute process current directory.
        """
    @property
    def minimal_path(self) -> typing.Optional[pathlib.Path]:
        r"""
        Optional absolute replacement for the platform minimal path.
        """
    def __new__(cls, current_directory: typing.Optional[builtins.str | os.PathLike[str] | pathlib.Path] = None, minimal_path: typing.Optional[builtins.str | os.PathLike[str] | pathlib.Path] = None) -> RuntimeContext: ...

@typing.final
class SandboxProcess:
    r"""
    A launched sandbox process and its detached standard streams.
    """
    def id(self) -> builtins.int:
        r"""
        Returns the native process identifier.
        """
    def has_stdin(self) -> builtins.bool:
        r"""
        Returns whether stdin is connected to a pipe.
        """
    def has_stdout(self) -> builtins.bool:
        r"""
        Returns whether stdout is connected to a pipe.
        """
    def has_stderr(self) -> builtins.bool:
        r"""
        Returns whether stderr is connected to a pipe.
        """
    def read_stdout(self, size: builtins.int) -> bytes:
        r"""
        Reads up to `size` bytes from stdout.
        """
    def read_stderr(self, size: builtins.int) -> bytes:
        r"""
        Reads up to `size` bytes from stderr.
        """
    def write_stdin(self, data: typing.Sequence[builtins.int]) -> builtins.int:
        r"""
        Writes bytes to stdin and returns the number written.
        """
    def close_stdin(self) -> None:
        r"""
        Closes the stdin pipe.
        """
    def try_wait(self) -> typing.Optional[ProcessResult]:
        r"""
        Returns the result without waiting, or `None` while running.
        """
    def wait(self) -> ProcessResult:
        r"""
        Waits until the process exits or its configured timeout fires.
        """
    def kill(self) -> None:
        r"""
        Terminates and confirms the complete sandbox boundary.
        """
    def close(self) -> None:
        r"""
        Terminates the process if needed and releases its native streams.
        """
    def wait_for(self) -> ProcessResult:
        r"""
        Compatibility alias for `wait()`.
        """
    def __enter__(self) -> SandboxProcess: ...
    def __exit__(self, _ty: typing.Optional[typing.Any], _value: typing.Optional[typing.Any], _traceback: typing.Optional[typing.Any]) -> builtins.bool: ...

class UnsupportedPlatformError(CageforgeError):
    r"""
    The requested Cageforge operation is unavailable on this platform.
    """
    ...

@typing.final
class WindowsSetup:
    r"""
    Explicit Windows setup operations, matching the JVM binding.
    """
    @staticmethod
    def is_supported() -> builtins.bool:
        r"""
        Returns whether this interpreter runs on Windows.
        """
    @staticmethod
    def install() -> None:
        r"""
        Installs or reconciles the owner-scoped Windows boundary.
        """
    @staticmethod
    def status() -> builtins.str:
        r"""
        Returns `"missing"`, `"stale"`, or `"ready"` without provisioning.
        """
    @staticmethod
    def verify() -> None:
        r"""
        Verifies the complete owner-scoped Windows setup.
        """
    @staticmethod
    def uninstall() -> None:
        r"""
        Removes the owner-scoped Windows boundary.
        """

def native_target() -> builtins.str: ...
